### PR TITLE
Fix circleci badge

### PR DESCRIPTION
**Pull request by rootulp**
Before | After
--- | ---
Screen Shot 2021-08-17 at 10 07 25 PM | https://circleci.com/gh/SetProtocol/set.js.svg?style=shield

Ref: https://circleci.com/docs/2.0/status-badges/

### CODE REVIEW

**Review by cgewecke — APPROVED** [review]
This *should* work ... when I check the url directly in a browser tab I see the badge resolving correctly.

Screen Shot 2021-08-30 at 9 28 57 AM

However, when I look at the README on [rootulp:patch-1][1], the link's broken...

Screen Shot 2021-08-30 at 9 33 01 AM

Going to merge and see what happens 🙂 . We can always revisit.

[1]: https://github.com/rootulp/set.js/tree/patch-1

**Comment by rootulp** [comment]
You're right, it doesn't appear to have resolved

Screen Shot 2021-08-30 at 8 17 10 PM

**Comment by cgewecke** [comment]
Screen Shot 2021-08-30 at 7 27 12 PM

Smh now it's working on my side. Might be a github or browser image cacheing delay.. think this good now though.

**Comment by rootulp** [comment]
🤯 this didn't work before I attempted https://github.com/SetProtocol/set.js/pull/73 but now it works

**Pull request merged**
